---
baseURL: "/"
languageCode: en-us
title: Belkirk College of Engineering
description: Belkirk Demo Site for Forestry.io
related:
  indices:
  - name: tags
    weight: 1
  - name: date
    weight: 2
    pattern: 2006
permalinks:
  people: "/about/:title/"
taxonomies:
  tag: tags
theme: forestry-demo
menu:
  footer:
  - name: About
    weight: 3
    identifier: about
  - name: Posts
    weight: 2
    identifier: posts
  - name: Projects
    weight: 1
    identifier: projects
  navigation:
  - name: Electric Vehicle
    parent: Projects
    weight: 1
