base ""dw]d wd w{ 
languageCode: "en-us"

title: Belkirk College of Engineering
theme: forestry-demo
description: Belkirk Demo Site for Forestry.io
related:
  indices:
    - name: tags
      weight: 1
    - name: date
      weight: 2
      pattern: 2006
permalinks:
  people: /about/:title/
taxonomies:
  tag: tags
params:
  short_title: Belkirk
  cloudinary: http://res.cloudinary.com/forestrydemo1/image/upload
