---
label: default
hide_body: false
is_partial: false
fields:
- type: tag_list
  name: tags
  label: Tags
- type: file
  name: banner_image
  label: Banner Image
  config:
    maxSize: '6'
- type: list
  name: ''
  label: ''
- type: field_group_list
  name: rfg
  label: rfg
  fields:
  - type: select
    name: whodat
    config:
      source:
        type: simple
      options:
      - test1
      - test2
    label: whodat
  - type: text
    name: tf
    label: tf
  config:
    labelField: whodat
pages:
- content/projects/gregt.md
- content/projects/prooj.md
